language: java
sudo: false
install: true
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.sonar
  - $HOME/.m2
  - kunta-api-server/.cargo
addons:
  hosts:
    - api.kunta-api.test
script: . travis.sh

notifications:
  email: false